name: Package

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 18.0.1
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18.0.1

      - name: Show Build Versions (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: .\gradlew.bat -v

      - name: Show Build Versions (Linux/macOS)
        if: ${{ runner.os != 'Windows' }}
        run: ./gradlew -v

      - name: Build with Gradle (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: .\gradlew.bat jpackage

      - name: Build with Gradle (Linux/macOS)
        if: ${{ runner.os != 'Windows' }}
        run: ./gradlew jpackage

      - name: Package zip distribution (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: .\gradlew.bat packageZipDistribution

      - name: Package zip distribution (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: ./gradlew packageZipDistribution

      - name: Package tar distribution (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: ./gradlew packageTarDistribution

      - name: Prepare macOS distributables
        if: ${{ runner.os == 'macOS' }}
        run: |
          cd build/jpackage
          ditto -c -k --sequesterRsrc --keepParent Ashigaru.app Ashigaru.app.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ashigaru Build - ${{ runner.os }}
          path: |
            build/distributions/*
            build/jpackage/*.dmg
            build/jpackage/*.pkg
            build/jpackage/*.msi
            build/jpackage/*.exe
            build/jpackage/*.deb
            build/jpackage/*.rpm
            build/jpackage/*.app.zip

      - name: Headless build with Gradle
        if: ${{ runner.os == 'Linux' }}
        run: ./gradlew -Djava.awt.headless=true clean jpackage

      - name: Package headless tar distribution
        if: ${{ runner.os == 'Linux' }}
        run: ./gradlew -Djava.awt.headless=true packageTarDistribution

      - name: Rename Headless Artifacts
        if: ${{ runner.os == 'Linux' }}
        run: for f in build/jpackage/ashigaru*; do mv -v "$f" "${f/ashigaru/ashigaru-server}"; done

      - name: Upload Headless Artifact
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v4
        with:
          name: Ashigaru Build - ${{ runner.os }} Headless
          path: |
            build/jpackage/*
            !build/jpackage/Ashigaru/
            build/distributions/*
